version: 2.1
jobs:
  test:
    working_directory: ~/fluency-meter-egistry
    docker:
      - image: circleci/openjdk:8u181-jdk
    environment:
      SBT_VERSION: 1.2.7
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
                    sudo apt update && sudo apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    sudo dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    sudo apt-get update
                    sudo apt-get install -y sbt python-pip git
                    sudo apt-get clean && sudo apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: Test fluency-meter-registry
          command: cat /dev/null | sbt clean test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  build-test:
    jobs:
      - test:
#          filters:
#            branches:
#              only:
#                - master

