name: CI

on: [push]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
        architecture: x64
    - name: Install SBT
      run: |
        sudo apt update && sudo apt install -y curl
        curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-1.2.8.deb
        sudo dpkg -i sbt-$SBT_VERSION.deb
        rm sbt-$SBT_VERSION.deb
        sudo apt-get update
        sudo apt-get install -y sbt
        sudo apt-get clean && sudo apt-get autoclean
    - name: Run test
      run: |
        cat /dev/null | sbt clean test
        
